server:
  port: 8888
spring:
  application:
    name: erudio-config-server
  profiles:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leandrocgsi/erudio-config-server
          default-label: main
          search-paths:
            - 'greeting-service*'
